apps/cms/urls.py
from django.urls import path
from . import views,staff_views

app_name = 'cms'

urlpatterns = [
    path('',views.index,name='index'),
    path('write_news/',views.WriteNews.as_view(),name='write_news'),
    path('news_category/',views.news_category,name='news_category'),
    path('add_news_category/',views.add_news_category,name='add_news_category'),
    path('qntoken/',views.qntoken,name='qntoken'),
    path('my_login/',views.my_login,name='my_login'),
    path('MyYogin/',views.login_view,name='MyYogin'),
    path('news_list/',views.NewsList.as_view(),name='news_list'),
]

urlpatterns += [
    path('staffs/',staff_views.staff_views,name='staffs'),
    path('add_staff/',staff_views.AddStaffView.as_view(),name='add_staff')
]

apps/cmsauth/urls.py
from django.urls import path
from . import views
app_name = 'cmsauth'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('register/',views.register_view,name='register'),
    # path('sms_captcha/',views.sms_captcha,name='sms_captcha'),
    # path('image_captcha/',views.image_captcha,name='image_captcha'),
    path('profile/',views.ProfileView.as_view(),name='profile'),
]

xfz_project/urls.py
from django.urls import path,include
from django.conf import settings
urlpatterns = [
    path('', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.cmsauth.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("__debug__/",include(debug_toolbar.urls)))

apps/cms/models.py
from django.db import models

# Create your models here.

apps/news/models.py
from django.db import models

# Create your models here.
class NewsCategory(models.Model):
    name = models.CharField(max_length=100)

class News(models.Model):
    title = models.CharField(max_length=200)
    desc = models.CharField(max_length=200)
    thumbnail = models.URLField()   # 存放缩略图的地址
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('NewsCategory',on_delete=models.SET_NULL,null=True)
    author = models.ForeignKey('cmsauth.User',on_delete=models.SET_NULL,null=True)

    class Meta:
        ordering = ['-pub_time']


class Comment(models.Model):
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    news = models.ForeignKey('News',on_delete=models.CASCADE,related_name='comments')
    author = models.ForeignKey('cmsauth.User', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-pub_time']

apps/cms/forms.py
from django import forms
from apps.news.models import News
from apps.forms import FormMixin

class WriteNewsForm(forms.ModelForm,FormMixin):
    category = forms.IntegerField()

    class Meta:
        model = News
        exclude = ['category','author','pub_time']

apps/cms/views.py
from django.shortcuts import render,redirect,reverse
from django.views.generic import View
from apps.news.models import NewsCategory,News
from utils import restful
from apps.cms.forms import WriteNewsForm
from django.views.decorators.http import require_GET,require_POST
import qiniu
from django.core.paginator import Paginator
from datetime import datetime
from django.utils.timezone import make_aware
from urllib import parse
from django.utils.decorators import method_decorator  #权限装饰器
from django.contrib.auth.decorators import permission_required

from apps.cmsauth.forms import LoginForm
from django.contrib.auth import login,authenticate
# Create your views here.

def index(request):
    return render(request,'cms/index.html')


@require_POST
def login_view(request):
    form = LoginForm(request.POST)
    if form.is_valid():
        telephone = form.cleaned_data.get('telephone')
        password = form.cleaned_data.get('password')
        remember = form.cleaned_data.get('remember')

        user = authenticate(request, username=telephone,password=password)
        if user:
            if user.is_active:
                login(request,user)
                if remember:
                    request.session.set_expiry(None)  # 默认保存两周
                else:
                    request.session.set_expiry(0)

                return redirect(reverse('cms:index'))
            else:
                return restful.unauth(message='您的账号未激活')
        else:
            return restful.params_error(message='手机号或者密码错误')
    else:
        errors = form.get_errors()
        return restful.params_error(message=errors)


# 列出文章
@method_decorator(permission_required(perm="news.view_news",login_url='/'),name='dispatch')   # 前面是模型的名字
class NewsList(View):
    def get(self,request):
        page = int(request.GET.get('p',1))
        start = request.GET.get('start')
        end = request.GET.get('end')
        title = request.GET.get('title')
        category_id = int(request.GET.get('category',0) or 0)
        newses = News.objects.select_related('category','author')
        if start or end:
            if start:
                start_date = datetime.strptime(start, '%Y/%m/%d')
            else:
                start_date = datetime(year=2019,month=6,day=1)
            if end:
                end_date = datetime.strptime(end, '%Y/%m/%d')
            else:
                end_date = datetime.today()
            newses = newses.filter(pub_time__range=(make_aware(start_date),make_aware(end_date)))
        if title:
            newses = newses.filter(title__icontains=title)
        if category_id:
            newses = newses.filter(category=category_id)


        paginator = Paginator(newses,2)
        page_obj = paginator.page(page)
        context_data = self.get_pagination_data(paginator,page_obj)
        context = {
            'newses':page_obj.object_list,  # 根据分页展示
            'paginator': paginator,
            'page_obj': page_obj,
            'categories': NewsCategory.objects.all(),
            'start': start,
            'end': end,
            'title': title,
            'category_id': category_id,
            'url_query': '&' + parse.urlencode({   # 将字典转换成 &start=&end=&title&category
                'start': start or '',
                'end':end or '',
                'title':title or '',
                'category':category_id or '',
            })
        }
        context.update(context_data)  # 更新数据
        return render(request,'cms/news_list.html',context=context)

    def get_pagination_data(self,paginator,page_obj,arround_count=2):
        current_page = page_obj.number  # 当前页码
        number_pages = paginator.num_pages  # 总共页数

        left_has_more = False
        right_has_more = False

        if current_page<=arround_count+2:
            left_pages = range(1,current_page)
        else:
            left_has_more = True
            left_pages = range(number_pages-arround_count,current_page)

        if current_page>=number_pages-arround_count-1:
            right_pages = range(current_page+1,number_pages+1)
        else:
            right_has_more = True
            right_pages = range(current_page+1,current_page+arround_count+1)

        return {
            'left_pages':left_pages,
            'right_pages':right_pages,
            'current_page':current_page,
            'left_has_more':left_has_more,
            'right_has_more':right_has_more,
            'number_pages':number_pages,
        }


def my_login(request):
    return render(request,'cms/login.html')

@method_decorator(permission_required(perm="news.add_news",login_url='/'),name='dispatch')   # 前面是模型的名字
class WriteNews(View):
    def get(self,request):
        categories = NewsCategory.objects.all()
        context = {
            'categories': categories
        }
        return render(request,'cms/write_news.html',context=context)

    def post(self,request):
        form = WriteNewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            category = NewsCategory.objects.get(pk=category_id)
            News.objects.create(title=title,desc=desc,category=category,thumbnail=thumbnail,content=content,author=request.user)
            return restful.success()
        else:
            return restful.params_error(message=form.get_errors())



@permission_required(perm='news_view_newscategory',login_url='/')
def news_category(request):
    categories = NewsCategory.objects.all()
    context = {
        'categories': categories
    }
    return render(request,'cms/news_category.html', context=context)

@permission_required(perm='news.add_newscategory',login_url='/')
def add_news_category(request):
    name = request.POST.get('name')
    exists = NewsCategory.objects.filter(name=name).exists()
    if exists:
        return restful.params_error(message='该分类以及存在')
    else:
        NewsCategory.objects.create(name=name)
        return restful.success()


@require_GET
def qntoken(request):
    access_key = 'UGn4NbCEOYgQ4mAa40VSoKf2CF5UtpDGhrDyMrNG'
    secret_key = 'VVB7j9NWeegSrO8uccmqPh4620OmFi6gCSprboO1'
    q = qiniu.Auth(access_key, secret_key)

    bucket = 'cuizhihao'   # 存储空间
    token = q.upload_token(bucket)
    return restful.result(data={"token":token})

front/templates/cms/add_staff.html
{% extends 'cms/base.html' %}

{% block title %}
    添加员工
{% endblock %}

{% block head %}

{% endblock %}

{% block content-header %}
<h1>添加员工</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="box">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="box-body">
                        <div class="form-group">
                            <label for="telephone-input">手机号码：</label>
                            <input type="text" class="form-control" name="telephone">
                        </div>
                        <div class="checkbox">
                            {% for group in groups %}
                                <label style="margin-right:20px;">
                                    <input type="checkbox" name="groups" value="{{ group.pk }}">{{ group.name }}
                                </label>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="box-footer">
                        <button class="btn btn-primary pull-right">立即添加</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %} | 小饭桌管理系统</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/qfajax.min.js' %}"></script>
    <script src="{% static 'js/xfzalert.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <header class="main-header">
        <!-- Logo -->
        <a href="/" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>CMS</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg">小饭桌后台</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{{ user.thumbnail }}"
                                 class="user-image" alt="User Image">
                            <span class="hidden-xs">{{ user.username }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="{{ user.thumbnail }}"
                                     class="img-circle" alt="User Image">
                                <p>
                                    {{ user.username }}
                                    <small>Python web开发工程师</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="{% url 'cmsauth:profile' %}" class="btn btn-default btn-flat">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{% url 'cms:my_login' %}" class="btn btn-default btn-flat">退出登录</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="首页">
                    <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
          </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="active">
                    <a href="{% url 'cms:index' %}">
                        <i class="fa fa-home"></i>
                        <span>首页</span>
                    </a>
                </li>
                    {% if perms.news.change_news %}
                    <li class="header">新闻管理</li>
                    <li>
                        <a href="{% url 'cms:news_list' %}">
                            <i class="fa fa-list"></i>
                            <span>新闻列表</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if perms.news.add_news %}
                    <li>
                        <a href="{% url 'cms:write_news' %}">
                            <i class="fa fa-edit"></i>
                            <span>发布新闻</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if perms.news.add_newscategory %}
                    <li>
                        <a href="{% url 'cms:news_category' %}">
                            <i class="fa fa-tag"></i>
                            <span>新闻分类</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if perms.news.add_banner %}
                    <li>
                        <a href="#">
                            <i class="fa fa-window-restore"></i>
                            <span>轮播图</span>
                        </a>
                    </li>
                    {% endif %}
                    {% if perms.course.change_course %}
                    <li class="header">课程管理</li>
                    <li>
                        <a href="#">
                            <i class="fa fa-tv"></i>
                            <span>发布课程</span>
                        </a>
                    </li>
                    {% endif %}

                    {% if user.is_superuser %}
                    <li class="header">员工管理</li>
                    <li>
                        <a href="{% url 'cms:staffs' %}">
                            <i class="fa fa-group"></i>
                            <span>员工管理</span>
                        </a>
                    </li>
                    {% endif %}
            </ul>
        </section>
    </aside>
    <div class="content-wrapper">
        <section class="content-header">
            {% block content-header %}{% endblock %}
        </section>
        <section class="content">
            {% block content %}{% endblock %}
        </section>

</body>
</html>

front/templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}首页{% endblock %}

{% block content-header %}
    <h1>Python学生管理系统</h1>
{% endblock %}
</html>

front/templates/cms/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>学生后台管理系统|登录</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/Ionicons/css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/iCheck/square/blue.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="#">小饭桌管理系统</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">请登录</p>

        <form action="{% url 'cms:MyYogin' %}" method="post">
            {% csrf_token %}
            <div class="form-group has-feedback">
                <input type="text" class="form-control" name="telephone" placeholder="请输入手机号码">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" class="form-control" name="password" placeholder="请输入密码">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="checkbox icheck">
                        <label>
                            <input type="checkbox" name="remember" value="1"> 记住我
                        </label>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
                </div>
                <!-- /.col -->
            </div>
        </form>
    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'adminlte/plugins/iCheck/icheck.min.js' %}"></script>
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' /* optional */
        });
    });
</script>
</body>
</html>

front/templates/cms/news_list.html
{% extends 'cms/base.html' %}


{% block title %}
    新闻列表
{% endblock %}

{% block head %}
    <style>
    .left-group{
        margin-right: 20px;
    }
    </style>
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script src="{% static 'js/news_list.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>新闻列表管理</h1>
{% endblock %}

{% block content %}
<div class="row">
<div class="col-md-12">
    <div class="box">
        <div class="box-header">
            <form action="" method="get" class="form-inline">
                <div class="form-group left-group">
                    <label for="">时间：</label>
                    {% if start %}
                        <input type="text" class="form-control" name="start" placeholder="起始时间" id="start-picker" readonly value="{{ start }}">
                    {% else %}
                        <input type="text" class="form-control" name="start" placeholder="起始时间" id="start-picker" readonly>
                    {% endif %}
                    <span>—</span>
                    {% if end %}
                        <input type="text" id="end-picker" class="form-control" name="end" placeholder="结束时间" readonly value="{{ end }}">
                    {% else %}
                        <input type="text" id="end-picker" class="form-control" name="end" placeholder="结束时间" readonly>
                    {% endif %}
                </div>
                <div class="form-group left-group">
                    <label for="title-input">标题：</label>
                    {% if title %}
                        <input type="text" class="form-control" name="title" id="title-input" placeholder="关键字" value="{{ title }}">
                    {% else %}
                        <input type="text" class="form-control" name="title" id="title-input" placeholder="关键字">
                    {% endif %}
                </div>
                <div class="form-group left-group">
                    <label for="category-input">分类：</label>
                    <select name="category" id="" class="form-control">
                        {% if category_id == 0 %}
                            <option value="0" selected>所有分类</option>
                        {% else %}
                            <option value="0">所有分类</option>
                        {% endif %}
                        {% for category in categories %}
                            {% if category_id == category.pk %}
                                <option value="{{ category.pk }}" selected>{{ category.name }}</option>
                            {% else %}
                                <option value="{{ category.pk }}">{{ category.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group left-group">
                    <button class="btn btn-primary">查询</button>
                </div>
                <div class="form-group">
                    <a href="{% url 'cms:news_list' %}">清除查询</a>
                </div>
            </form>
        </div>
        <div class="box-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>标题</th>
                        <th>分类</th>
                        <th>发布时间</th>
                        <th>作者</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {% for news in newses %}
                        <tr>
                            <td><a target="_blank" href="#">{{ news.title }}</a></td>
                            <td>{{ news.category.name }}</td>
                            <td>{{ news.pub_time }}</td>
                            <td>{{ news.author.username }}</td>
                            <td>
                                <a href="" class="btn btn-info btn-xs">编辑</a>
                                <button class="btn btn-danger btn-xs delete-btn" data-news-id="{{ news.pk }}">删除</button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="box-footer">
            <p class="pull-left">第{{ current_page }}页/总共{{ number_pages }}页</p>
            <ul class="pagination pull-right">
                {#上一页#}
                {% if page_obj.has_previous %}
                    <li><a href="?p={{ page_obj.previous_page_number }}{{ url_query }}">上一页</a></li>
                {% else %}
                    <li class="disabled"><a href="javascript:void(0);">上一页</a></li>
                {% endif %}

                {# 是否需要出现三个点 #}
                {% if left_has_more %}
                    <li><a href="?p=1">1</a></li>
                    <li><a href="javascript:void(0);">...</a></li>
                {% endif %}

                {# 左边的页码 #}
                {% for left_page in left_pages %}
                    <li><a href="?p={{ left_page }}{{ url_query }}">{{ left_page }}</a></li>
                {% endfor %}

                {# 当前的页面 #}
                <li class="active"><a href="?p={{ current_page }}{{ url_query }}">{{ current_page }}</a></li>

                {# 右边的页码 #}
                {% for right_page in right_pages %}
                    <li><a href="?p={{ right_page }}{{ url_query }}">{{ right_page }}</a></li>
                {% endfor %}

                {# 用来控制右边三个点 #}
                {% if right_has_more %}
                    <li><a href="javascript:void(0);">...</a></li>
                    <li><a href="?p={{ number_pages }}{{ url_query }}">{{ number_pages }}</a></li>
                {% endif %}

                {#下一页#}
                {% if page_obj.has_next %}
                    <li><a href="?p={{ page_obj.next_page_number }}{{ url_query }}">下一页</a></li>
                {% else %}
                    <li class="disabled"><a href="javascript:void(0);">下一页</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
</div>
{% endblock %}

front/templates/cms/staffs.html
{% extends 'cms/base.html' %}

{% block title %}员工管理{% endblock %}

{% block head %}

{% endblock %}

{% block content-header %}
<h1>员工管理</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <a href="{% url 'cms:add_staff' %}" class="btn btn-primary pull-right">添加员工</a>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>用户名</th>
                                <th>手机号</th>
                                <th>所属分组</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for staff in staffs %}
                            <tr>
                                <td>{{ staff.username }}</td>
                                <td>{{ staff.telephone }}</td>
                                <td>
                                    {% if staff.is_superuser %}
                                        超级管理员
                                    {% else %}
                                        {% for group in staff.groups.all %}
                                            {{ group.name }}/
                                        {% endfor %}
                                    {% endif %}
                                </td>
                                <td>
                                    <button class="btn btn-info btn-xs" >编辑</button>
                                    <button class="btn btn-danger btn-xs" href="{% url 'cms:add_staff' %}">删除</button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="box-footer"></div>
            </div>
        </div>
    </div>
{% endblock %}