apps/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('',views.index,name='index'),
    path('<int:news_id>/',views.news_detail,name='news_detail'),
    path('list/',views.news_list,name='news_list'),
    path('pub_comment/',views.public_comment,name='pub_comment'),
]

xfz_project/urls.py
from django.urls import path,include
from django.conf import settings
urlpatterns = [
    path('', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.cmsauth.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("__debug__/",include(debug_toolbar.urls)))

apps/news/models.py
from django.db import models

# Create your models here.
class NewsCategory(models.Model):
    name = models.CharField(max_length=100)

class News(models.Model):
    title = models.CharField(max_length=200)
    desc = models.CharField(max_length=200)
    thumbnail = models.URLField()   # 存放缩略图的地址
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('NewsCategory',on_delete=models.SET_NULL,null=True)
    author = models.ForeignKey('cmsauth.User',on_delete=models.SET_NULL,null=True)

    class Meta:
        ordering = ['-pub_time']


class Comment(models.Model):
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    news = models.ForeignKey('News',on_delete=models.CASCADE,related_name='comments')
    author = models.ForeignKey('cmsauth.User', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-pub_time']

apps/news/forms.py
from django import forms
from apps.forms import FormMixin
class PublicCommentForm(forms.Form):
    content = forms.CharField()
    news_id = forms.IntegerField()

apps/news/views.py
from django.shortcuts import render
from apps.news.models import NewsCategory,News
from django.conf import settings
from django.http import Http404
from .serializers import NewsSerializers,CommentSerializers
from utils import restful
from .forms import PublicCommentForm
from .models import Comment

# Create your views here.
def index(request):
    count = settings.ONE_PAGE_NEWS_COUNT
    newses = News.objects.select_related('category','author').all()[0:count]
    categories = NewsCategory.objects.all()
    context = {
        'newses': newses,
        'categories': categories,
    }
    return render(request,'news/index.html',context=context)

def news_detail(request,news_id):
    try:
        news = News.objects.select_related('category','author').prefetch_related('comments').get(pk=news_id)
        context = {
            'news': news
        }
        return render(request,'news/news_detail.html',context=context)
    except News.DoesNotExist:
        raise Http404

def news_list(request):

    #通过 p参数 获取用户想查看第几页
    page = int(request.GET.get('p',1))
    category_id = int(request.GET.get('category_id',0))

    #1 0 1  2
    #2 2 3  4
    #3 4 5  6
    start = (page-1)*settings.ONE_PAGE_NEWS_COUNT
    end = start + settings.ONE_PAGE_NEWS_COUNT
    if category_id == 0:
        newses = News.objects.select_related('category','author').all()[start:end]
    else:
        newses = News.objects.select_related('category', 'author').filter(category__id=category_id)[start:end]

    serializer = NewsSerializers(newses,many=True)  # 每一条都要序列化成json
    data = serializer.data
    return restful.result(data=data)

# 评论
def public_comment(request):
    form = PublicCommentForm(request.POST)
    if form.is_valid():
        news_id = form.cleaned_data.get('news_id')
        content = form.cleaned_data.get('content')
        news = News.objects.get(pk=news_id)
        comments = Comment.objects.create(content=content,news=news,author=request.user)
        serializer = CommentSerializers(comments)
        data = serializer.data
        return restful.result(data=data)
    else:
        return restful.params_error(message=form.get_errors)

front/templates/news/index.html
{% extends 'base/front_base.html' %}

{% block title %}首页{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/news/index.min.css' %}">
    <script src="{% static 'arttemplate/template-web.js' %}"></script>
    <script src="{% static 'js/index.min.js' %}"></script>
    {# 这个区域用来显示  ajax异步返回的 json信息   为了 防止 变量标签跟django模板引擎冲突 我们使用{% verbatim %} {% endverbatim %} 给它包裹起来#}

{#引用其他的模板引擎#}
<script id="news-item" type="text/html">
    {% verbatim %}
    {{ each newes news index }}
    <li>
        <div class="thumbnail-group">
            <a href="/{{ news.id }}">
                <img src="{{ news.thumbnail }}" alt="">
            </a>
        </div>
        <div class="news-group">
            <p class="title">
                <a href="/{{ news.id }}">{{ news.title }}</a>
            </p>
            <p class="desc">
                {{ news.desc }}
            </p>
            <p class="more">
                <span class="category">{{ news.category.name }}</span>
                <span class="pub-time">{{ news.pub_time  }} </span>
                <span class="author">{{ news.author.username }}</span>
            </p>
        </div>
    </li>
    {{ /each }}
    {% endverbatim %}
</script>
{% endblock %}

{% block main %}
    <div class="main">
        <div class="wrapper">
            <div class="main-content-wrapper">
                <div class="banner-group" id="banner-group">
                    <ul class="banner-ul" id="banner-ul">
                        {% for banner in banners %}
                            <li>
                                <a href="{{ banner.link_to }}">
                                    <img src="{{ banner.image_url }}" alt="">
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                    <span class="arrow left-arrow">‹</span>
                    <span class="arrow right-arrow">›</span>
                    <div class="page-control-group">
                        <ul class="page-control">
                        </ul>
                    </div>
                </div>
                <div class="list-outer-group">
                    <ul class="list-tab">
                        <li data-category="0"><a href="javascript:void(0);">最新资讯</a></li>
                        {% for category in categories %}
                            <li data-category="{{ category.pk }}"><a href="javascript:void(0);">{{ category.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                    <ul class="list-inner-group">
                        {% for news in newses %}
                            <li>
                                <div class="thumbnail-group">
                                    <a href="{% url 'news:news_detail' news_id=news.pk %}">
                                        <img src="{{ news.thumbnail }}" alt="">
                                    </a>
                                </div>
                                <div class="news-group">
                                    <p class="title">
                                        <a href="{% url 'news:news_detail' news_id=news.pk %}">{{ news.title }}</a>
                                    </p>
                                    <p class="desc">
                                        {{ news.desc }}
                                    </p>
                                    <p class="more">
                                        <span class="category">{{ news.category.name }}</span>
                                        <span class="pub-time">{{ news.pub_time  }} </span>
                                        <span class="author">{{ news.author.username }}</span>
                                    </p>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                    <div class="load-more-group">
                        <button class="load-more" id="load-more-btn">查看更多</button>
                    </div>
                </div>
            </div>
            {% include 'common/sidebar.html' %}
        </div>
    </div>
{% endblock %}

front/templates/news/news_category.html
{% extends 'cms/base.html' %}

{% block title %}
    新闻分类
{% endblock %}

{% block head %}
    <script src="{% static 'js/news_category.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>新闻分类</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <button id="add-btn" class="btn btn-primary pull-right">添加分类</button>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>分类名称</th>
                                <th>新闻数量</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for category in categories %}
                                <tr data-pk="{{ category.pk }}" data-name="{{ category.name }}">
                                    <td>{{ category.name }}</td>
                                    <td>20</td>
                                    <td>
                                        <button class="btn btn-warning btn-xs edit-btn">编辑</button>
                                        <button class="btn btn-danger btn-xs delete-btn">删除</button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/news/news_detail.html
{% extends 'base/front_base.html' %}
{#{% load tmp_filter %}#}

{% block title %}
    新闻详情页
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/news/news_detail.min.css' %}">
    <script src="{% static 'arttemplate/template-web.js' %}"></script>
    <script src="{% static 'js/news_detail.min.js' %}"></script>
<script id="comment-item" type="text/html">
{% verbatim %}
<li>
    <div class="comment-info">
        <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1528129845916&di=536993042d5223862f8c4ab157ba6e72&imgtype=0&src=http%3A%2F%2Fpic1.ipadown.com%2Fimgs%2F201206120933354195.jpg" alt="" class="avatar">
        <span class="author">{{ comment.author.username }}</span>
        <span class="pub-time">{{ comment.pub_time }}</span>
    </div>
    <p class="comment-content">{{ comment.content }}</p>
</li>
{% endverbatim %}
</script>
{% endblock %}

{% block main %}
    <div class="main">
        <div class="wrapper">
            <div class="main-content-wrapper">
                <div class="news-wrapper">
                    <h1 class="title">{{ news.title }}</h1>
                    <div class="news-info">
                        <div class="info-group">
                            <span class="author">{{ news.author.username }}</span>
                            <span class="pub-time">{{ news.pub_time }}</span>
                            <span class="category">{{ news.category.name }}</span>
                        </div>
                        <div class="share-group">
                            <span>分享至：</span>
                            <a class="weixin share-item"></a>
                            <a href="#" class="weibo share-item"></a>
                        </div>
                    </div>
                    <article class="article">
                        {{ news.content|safe }}
                    </article>
                </div>
                <div class="comment-wrapper">
                    <h3 class="title">文章评论（0）</h3>
                    <textarea name="comment" class="comment-textarea logined-textarea" placeholder="立即登录，参与评论~"></textarea>
                    <div class="submit-btn-group">
                        <button class="submit-btn" data-news-id="{{ news.pk }}">立即评论</button>
                    </div>
                    <ul class="comment-list">
                        {% for comment in news.comments.all %}
                            <li>
                                <div class="comment-info">
                                    <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1528129845916&di=536993042d5223862f8c4ab157ba6e72&imgtype=0&src=http%3A%2F%2Fpic1.ipadown.com%2Fimgs%2F201206120933354195.jpg" alt="" class="avatar">
                                    <span class="author">{{ comment.author.username }}</span>
                                    <span class="pub-time">{{ comment.pub_time}}</span>
                                </div>
                                <p class="comment-content">{{ comment.content }}</p>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% include 'common/sidebar.html' %}
        </div>
    </div>
{% endblock %}